### PR TITLE
Prevent warning autoload composer

### PR DESCRIPTION
**Pull request by geidsonc**
- Change name the class AdSense
- Rename class Google_Service_Compute_HTTPSHealthCheck to Google_Service_Compute_HttpsHealthCheck

### CODE REVIEW

**Comment by geidsonc** [comment]
@googlebot I signed it!

**Comment by dwsupplee** [comment]
Thank you @geidsonc, unfortunately this would likely get overwritten as we use automated tooling on this repository. I'm looking in to what happened with the casing.

**Comment by geidsonc** [comment]
@dwsupplee, I was not aware of that. I will close pull request. Thanks.

**Comment by florinpatrascu** [comment]
Hi there - are there any updates about this issue? We can still see related errors, ie

```elixir
[error] beam/beam_load.c(1440): Error loading module 'Elixir.Poison.Decoder.GoogleApi.Compute.V1.Model.HTTPSHealthCheck':
  BEAM file exists but it defines a module named Elixir.Poison.Decoder.GoogleApi.Compute.V1.Model.HttpsHealthCheck
```

thank you

**Pull request closed without merging**
