### PR TITLE
Add `@var` to Model Properties to Primitive Types

### PR DESCRIPTION
**Pull request by chrisguitarguy**
:wave: I've had this PR open on the api client generator for a while https://github.com/google/apis-client-generator/pull/44

That adds `@var`, `@param`, and `@return` to model properties with primitive types. Thought I would try to get it merged here since I suspect y'all don't use that `apis-client-generator` libary, but instead use the `generator/` here.

I also fixed the tests in `php_generator_test.py` so they pass, but did not add any further tests. I can do that if you'd like.

Here's a sample patch on `Google\Service\DisplayVideo\Advertiser`

```patch
diff --git a/src/DisplayVideo/Advertiser.php b/src/DisplayVideo/Advertiser.php
index b98a7c056..db9eca38a 100644
--- a/src/DisplayVideo/Advertiser.php
+++ b/src/DisplayVideo/Advertiser.php
@@ -21,22 +21,43 @@ class Advertiser extends \Google\Model
 {
   protected $adServerConfigType = AdvertiserAdServerConfig::class;
   protected $adServerConfigDataType = '';
+  /**
+   * @var string
+   */
   public $advertiserId;
   protected $creativeConfigType = AdvertiserCreativeConfig::class;
   protected $creativeConfigDataType = '';
   protected $dataAccessConfigType = AdvertiserDataAccessConfig::class;
   protected $dataAccessConfigDataType = '';
+  /**
+   * @var string
+   */
   public $displayName;
+  /**
+   * @var string
+   */
   public $entityStatus;
   protected $generalConfigType = AdvertiserGeneralConfig::class;
   protected $generalConfigDataType = '';
   protected $integrationDetailsType = IntegrationDetails::class;
   protected $integrationDetailsDataType = '';
+  /**
+   * @var string
+   */
   public $name;
+  /**
+   * @var string
+   */
   public $partnerId;
+  /**
+   * @var bool
+   */
   public $prismaEnabled;
   protected $servingConfigType = AdvertiserTargetingConfig::class;
   protected $servingConfigDataType = '';
+  /**
+   * @var string
+   */
   public $updateTime;
 
   /**
@@ -53,10 +74,16 @@ class Advertiser extends \Google\Model
   {
     return $this->adServerConfig;
   }
+  /**
+   * @param string
+   */
   public function setAdvertiserId($advertiserId)
   {
     $this->advertiserId = $advertiserId;
   }
+  /**
+   * @return string
+   */
   public function getAdvertiserId()
   {
     return $this->advertiserId;
@@ -89,18 +116,30 @@ class Advertiser extends \Google\Model
   {
     return $this->dataAccessConfig;
   }
+  /**
+   * @param string
+   */
   public function setDisplayName($displayName)
   {
     $this->displayName = $displayName;
   }
+  /**
+   * @return string
+   */
   public function getDisplayName()
   {
     return $this->displayName;
   }
+  /**
+   * @param string
+   */
   public function setEntityStatus($entityStatus)
   {
     $this->entityStatus = $entityStatus;
   }
+  /**
+   * @return string
+   */
   public function getEntityStatus()
   {
     return $this->entityStatus;
@@ -133,26 +172,44 @@ class Advertiser extends \Google\Model
   {
     return $this->integrationDetails;
   }
+  /**
+   * @param string
+   */
   public function setName($name)
   {
     $this->name = $name;
   }
+  /**
+   * @return string
+   */
   public function getName()
   {
     return $this->name;
   }
+  /**
+   * @param string
+   */
   public function setPartnerId($partnerId)
   {
     $this->partnerId = $partnerId;
   }
+  /**
+   * @return string
+   */
   public function getPartnerId()
   {
     return $this->partnerId;
   }
+  /**
+   * @param bool
+   */
   public function setPrismaEnabled($prismaEnabled)
   {
     $this->prismaEnabled = $prismaEnabled;
   }
+  /**
+   * @return bool
+   */
   public function getPrismaEnabled()
   {
     return $this->prismaEnabled;
@@ -171,10 +228,16 @@ class Advertiser extends \Google\Model
   {
     return $this->servingConfig;
   }
+  /**
+   * @param string
+   */
   public function setUpdateTime($updateTime)
   {
     $this->updateTime = $updateTime;
   }
+  /**
+   * @return string
+   */
   public function getUpdateTime()
   {
     return $this->updateTime;
```

### CODE REVIEW

**Comment by chrisguitarguy** [comment]
image

**Comment by bshaffer** [comment]
@chrisguitarguy we renamed the branch from `master` to `main` and I deleted the branch instead of using the "rename branch" feature (my bad), so all the PRs were automatically closed.

**Comment by bshaffer** [comment]
@chrisguitarguy Sorry for the inconvenience. Would you mind reopening your PR against the `main` branch?

**Comment by chrisguitarguy** [comment]
@bshaffer done!

**Pull request closed without merging**
