### PR TITLE
fix: returns array on empty array/map properties

### PR DESCRIPTION
**Pull request by PaolaRuby**
https://github.com/googleapis/google-api-php-client-services/pull/2258 alternative

### CODE REVIEW

**Comment by PaolaRuby** [comment]
@jacekkarczmarczyk ideas??

**Review by bshaffer — APPROVED** [review]

**Comment by bshaffer** [comment]
@PaolaRuby looking at the updated tests, I am not sure this is going to fix the issue

**Comment by parallels999** [comment]
@bshaffer why? it is going back to null on map, and it not returns null on getters

**Comment by maxnz** [comment]
It looks like these changes were re-released automatically as part of v0.290.0?
https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.290.0

**Pull request closed without merging**
